### ISSUE TITLE
modify youtube embed code

### ISSUE THREAD

**Issue by nerijus** [requestly/chrome-extension#100]
I would like to change in a web page:
<embed src="http://www.youtube.com/v/Ovq4GPHL3jI?version=3" type="application/x-shockwave-flash"  width="600"...
to
<embed src="http://www.youtube.com/embed/Ovq4GPHL3jI?version=3"  width="600"...
i.e. I want to change .../v/... to .../embed/... and remove type="application/x-shockwave-flash".
I entered 2 rules:
1. Replace http://www.youtube.com/v/ with http://www.youtube.com/embed/
It seems to work.
2. Replace type="application/x-shockwave-flash" with  (I entered space here). But it does not seem to work.

**Comment by blunderboy** [comment]
@nerijus There are couple of things you should note
1. You can modify network requests with Requestly So with replace rule you can change the rule and its working fine. 
2. You can not modify attribute types with requestly. In your case, type="application/x-shockwave-flash" is an attribute of embed element which is not related to Network Requests. Hence, you can not modify it.

Let me know if you need further help.
