### ISSUE TITLE
a backtick on rule-index panel 

### ISSUE THREAD

**Issue by gjccing** [requestly/chrome-extension#112]
Hi @blunderboy,

Your extension is very helpful to my job. 
I find a `` ` `` at the end of the [`SharedListIndex.hbs`](https://github.com/requestly/chrome-extension/blob/master/src/pages/templates/SharedListIndex.hbs). 
Maybe It is an unnecessary character.

Thanks

**Comment by blunderboy** [comment]
Thanks @gjccing. I have fixed this issue in above commit. I am glad that you find this tool very useful.
Closing this!!

**Comment by blunderboy** [comment]
This issue also exists in RuleIndex.hbs and SharedListIndex.hbs.

**Comment by blunderboy** [comment]
Fixed this issue in two other files as well. Closing this ticket.
