### ISSUE TITLE
Need help with this extension please

### ISSUE THREAD

**Issue by semicodin** [requestly/chrome-extension#126]
I'm trying to disable a redirect on the virginmobileusa.com store.  The page I **want** to land on is Virgin's (US) Shopping site for Paylo cellphones (not the top-up cards, the actual phones themselves) at

[https://www.virginmobileusa.com/#!/shop/phones/@PayLo/](url)

. . . but the site keep bouncing me to
[https://www.virginmobileusa.com/#!/shop/phones/](url)

I've tried numerous _redirect-disable_ Chrome extensions, none of which work.  I am a beginner at this so if you have script/settings examples I can follow, please provide a link.  If you suspect your extension won't work for my particular operation could you let me know?  or alternate Chrome extensions if you know of any that might be particularly useful.  Thanks

semicodin

**Comment by blunderboy** [comment]
@semicodin I tried opening https://www.virginmobileusa.com/#!/shop/phones/@PayLo/ in browser but I am never able to open this. Looks like their javascript implementation is not allowing you to go to that link.

Requestly allows you to modify the URLs and you can setup a rule to go directly to the Url you want but their javascript handler (ng-router to be specific) is getting invoked which takes you back to all phones route. 

Either there is no phone available in `Paylo` category or there is something site specific.

**Comment by semicodin** [comment]
Blunder boy, hey thanks for getting back to me.  What's so frustrating about this is there **is** at least one phone listed (a cheap Alcatel) but, fair enough.  What a fantastic extension.  Can I ask, do you have a page/site with specific scripting examples that I could study?  I don't want to impose upon your time with beginner questions. :)

**Comment by blunderboy** [comment]
@semicodin Thanks man!! Glad you liked the extension. Actually, I don't have a very rich source of examples or documentation but I believe the interface is very simple and intuitive. I can give you some examples here itself.

Example 1: Suppose you find an issue in your JS code on your website.
You can copy that JS code and host it locally say (localhost:8080/main.js) Now you fix your bug in the local file and use requestly to redirect js present on website to your locally hosted file and confirm the fix.
To setup  a redirect rule, you can follow following steps:
1. Create a redirect rule
2. Select Source contains "http://mywebsite.com/some.js" 
3. Destination "http://localhost:8080/main.js"

And save the rule. Now, whenever the request is made for `somejs`, requestly will redirect this to your localhost js and you can test your fix on the site.

Example 2: Very simple one
1. Create redirect rule
2. Source contains yahoo.com
3. Destination facebook.com

Try opening cricket.yahoo.com in your browser and it should take you to facebook. 

Example 3: Block websites
1. Create Cancel Rule
2. Source contains facebook
3. Click on Add Pairs
4. Source contains twitter
5. Save the rule

Now, try to open twitter.com and your browser should do nothing.

Let me know if there is any specific use case. Happy to help!!

**Comment by blunderboy** [comment]
@semicodin Closing this issue assuming your question is answered. Please reopen or open another one if you want to know something more. Thanks!!
