### ISSUE TITLE
invalid Adblocker warning, 403 on /showads.js - blocking usage

### ISSUE THREAD

**Issue by DanCuccia** [requestly/chrome-extension#132]
![error](https://cloud.githubusercontent.com/assets/5194693/15610766/fc71118a-23f4-11e6-8e9a-e024b01e16bf.png)

I've starting getting these errors which block the page from usage - as per Sachin's comment, showads.js is getting a 403 and is causing this.

PS: I can still use the page after deleting the backdrop elements.

**Comment by blunderboy** [comment]
Thanks @DanCuccia for logging the issue. If there is no adblocker, there has to be some extension in your browser which is blocking these resources for Requestly. Can you please provide the list of extensions you are using.

showads.js just sets a flag `window.canShowAds = true` and since your script gets 403, the other code thinks you have AdBlocker installed so it shows you backdrop.

1. Please list your browser extensions. 
2. Can you try to open http://web.requestly.in in Chrome Incognito window and in Firefox ?

**Comment by blunderboy** [comment]
@DanCuccia Could you tell if this issue is fixed for you or are you still seeing this error. Its really weird that those network calls are failing for you. I am pretty sure there is something in your browser which is cancelling those requests. I am very curious to know what caused this.

**Comment by blunderboy** [comment]
@DanCuccia Any update here ?

**Comment by DanCuccia** [comment]
Hey @blunderboy my apologies for the delay, unfortunately we still see the adblocker message displaying. As requested here are the extensions which I currently have installed:
-Cisco WebEx Extension
-Page Ruler
-Flip the Script
-Full Page Screen Capture
-and of course, Requestly

Opening in incognito as well as FireFox also produces the message.

If it helps, here's the request headers:
![403 request](https://cloud.githubusercontent.com/assets/5194693/15944501/e790dec8-2e5b-11e6-94d6-4fd15cb849aa.PNG)

**Comment by blunderboy** [comment]
Thanks @DanCuccia for your response. Hmm none of your extensions look to block the script. This is totally weird that this particular request is getting 403 out of nowhere.

I believe none of your extensions are enabled in Incongnito mode and still you get that error. Can you please answer me couple of questions:

1. Are you behind some kind of firewall ?
2. Are you able to load the script http://web.requestly.in/js/scripts/showads.js in an empty tab ?

I have not heard of any complaints from any other user so it definitely looks to be a problem with your network. Thanks man for providing help so far!!

**Comment by sachinjain024** [comment]
@DanCuccia Any update here ?

**Comment by DanCuccia** [comment]
Hey @sachinjain024 - We are no longer receiving the ad-blocker message, thanks for the help

**Comment by sachinjain024** [comment]
@DanCuccia Glad to know man!!
