### ISSUE TITLE
Add grunt task to build project locally

### ISSUE THREAD

**Issue by lazyvab** [requestly/chrome-extension#134]
Currently, I see below tasks none of which can be used just to build the project locally.

> grunt.registerTask('templates', ['handlebars']);
> grunt.registerTask('libs', ['handlebars', 'concat']);
> grunt.registerTask('build', ['handlebars', 'sass', 'concat', 'zipup']);
> grunt.registerTask('test', ['karma:unit']);
> grunt.registerTask('dev', ['watch']);

**Comment by lazyvab** [comment]
@blunderboy I want to make below 2 changes:
A-   grunt.registerTask('build', ['handlebars', 'sass', 'concat']);
M-   grunt.registerTask('bundle', ['build', 'zipup']);

Are you fine with this?

**Comment by blunderboy** [comment]
@lazyvab looks good to me. Please go ahead and make a direct commit to master.

**Comment by lazyvab** [comment]
Committed to master.
