### ISSUE TITLE
Adding additional text after URL

### ISSUE THREAD

**Issue by PiggyWhiskey** [requestly/chrome-extension#135]
I'm trying to set up a "Replace Host" rule that takes a unique ID from the URL and uses it in another,

Example
In: company.com/abc/[Unique Code]
Out: company2.com/xyz/[Unique Code]_123.def

I can easily substitute the first with a simple rule, but I'm not sure how to add the extra's on the end of the URL

Any tips?

**Comment by blunderboy** [comment]
@PiggyWhiskey You can setup a Redirect Rule like this

    Source Url  - `Matches` `/company\.com\/abc\/(.+)
    Destination - company2.com/xyz/$1

Let me know if it helps.

**Comment by PiggyWhiskey** [comment]
Works perfectly :) Thanks.

Sorry for what must seem like a very simple question

**Comment by sachinjain024** [comment]
@PiggyWhiskey No problems man!! Glad I could help
