### ISSUE TITLE
Add functionality to clear cache directly from popup with a single click

### ISSUE THREAD

**Issue by blunderboy** [requestly/chrome-extension#23]
Roughly this functionality is already implemented in [Clear Cache](https://chrome.google.com/webstore/detail/clear-cache/cppjkneekbjaeellbfkmgnhonkkjfpdn) extension but it is good to have in Requestly as well.

**Comment by jainrahul983** [comment]
do we need to add a button to clear cache??

**Comment by blunderboy** [comment]
@jainrahul983 Actually, this is not well thought till this point. I have to work on the User requirements and define phase in order to start on it. Let's skip it for now.

**Comment by jainrahul983** [comment]
ok

**Comment by blunderboy** [comment]
Probably, we can add an option to clear cache as right click option. But do we really need it ?
Closing this. Will reopen if required.
