### ISSUE TITLE
avoid chrome auto URLEncode/URLDecode

### ISSUE THREAD

**Issue by douniwan5788** [requestly/chrome-extension#85]
My company has `.exe` file download restrictions, So I try to bypass it by using requestly change the url to `%%32Eexe` (Chrome auto URLDecode once before really send the request), and it works like a charm!

But last time I checked, Chrome somehow begin URLEncode too, so the url become `%252Eexe`, Can requestly avoid chrome auto URLEncode/URLDecode? Or is there any way to escape it?

**Comment by blunderboy** [comment]
@douniwan5788 Thanks for opening an issue. As for your answer, I can not answer it for now. May be requestly can help you solve this problem. I would like to know the rule you have used earlier which was working for you. You can replace any sensitive information with dummy fields. Once I understand your use case I can try to figure out a solution for you.

**Comment by douniwan5788** [comment]
I use a **Redirect Request Rule**  with *Url matches*=`/(http:.*)\.exe$/` *Destination*=`$1%%32Eexe`

**Comment by blunderboy** [comment]
@douniwan5788 After a bit of fiddling with Urls, I was unable to get past chrome with a Url with just escaped value of `.` (dot). I have asked a question on StackOverflow here: http://stackoverflow.com/questions/33906886/how-to-encode-dot-in-url

**Comment by blunderboy** [comment]
Sorry @douniwan5788 . Its bit of time since I last revisited this and I did not find any solution on Stakoverflow as well. Closing this.
