### ISSUE TITLE
Add a timer (Imported from Chrome Store Support)

### ISSUE THREAD

**Issue by blunderboy** [requestly/chrome-extension#88]
Hi, first of all, thanks to all programmers involved in this project.
I wanna know if you guys can add a timer, like EasyAutoRefresh and other. 
I'm back-end developer & network manager and i need something like that. If you need my help, i'll be willing and able.

https://chrome.google.com/webstore/detail/requestly/mdnleldcmiljblolnjhpnblkcekpdkpa/support

**Comment by blunderboy** [comment]
OP, Can you please share the details what do you need ?
What are the use cases which are not achieved with EasyAutoRefresh ?

I can happily add some new features. Just let me know the specifics.

**Comment by reilue** [comment]
Hi again, Eulier here.
Hi, first of all, thanks to all programmers involved in this project.
I wanna know if you guys can add a timer, like EasyAutoRefresh and other. I'm back-end developer & network manager and i need something like that. If you need my help, i'll be willing and able.

What exaclty i need is following:
- Timer on the Redirect Request

**Comment by blunderboy** [comment]
@reilue Do you want to redirect request after a certain time and not instantly ?

Code for redirecting a Url is here: https://github.com/requestly/chrome-extension/blob/master/src/background/background.js#L202

**Comment by reilue** [comment]
Exactly man!

**Comment by blunderboy** [comment]
@reilue I am afraid there is no such official thing I can do to support delay in network request. There is only one hack which probably you can do after taking a local build, is to run an empty loop to lapse some time and then return from the method. 

Code will look something like this:

    function sleep (seconds) {
      var start = new Date().getTime();
      while (new Date() < start + seconds*1000) {}
      return 0;
    }
    sleep(2);

We will call this method before redirecting the Url.

Will this approach work for you ?
I can then add this code and share a build with you with the changes.

**Comment by reilue** [comment]
Exaclty that should work, but where should i put that code in background.js?.
If you can add that code and share, it will be an honor. Otherwise if you're too busy just tell me where to throw the code in js file.

**Comment by blunderboy** [comment]
@reilue Alright. I can add the code and share the zip with you.
Please allow me sometime and I will revert with zip and I can show you a commit to do it yourself next time in case you want to take latest code in future and redo the changes.

**Comment by blunderboy** [comment]
@reilue I have attached a build which you can easily unzip and load into your browser by following these steps:

1. Go to chrome://extensions
2. Select Developer Mode checkbox
3. Load Unpacked extension
4. Select the folder where you unzipped the code

For code change, you can have a look at the following commit: https://github.com/requestly/chrome-extension/commit/d20ccd02821311cc5422fd9922ad9e5faf2d554d

It was fairly simple change and you should be able to do it next time when you want to pull latest changes. I have added a sample usage in case of redirect request. I have added comments where you want to add in case of "Cancel Rule" and "Replace Rule" So just add sleep timer based on your use case.

I have tried this and it worked fine. Let me know if you need any more help!!

[Requestly_3.5.4_2015-12-16_092755.zip](https://github.com/requestly/chrome-extension/files/63526/Requestly_3.5.4_2015-12-16_092755.zip)

**Comment by blunderboy** [comment]
@reilue Did you get a chance to try this out ? Let me know if it works for you.

**Comment by reilue** [comment]
Great!!!, let me test it.

**Comment by blunderboy** [comment]
@reilue What do you mean by load url. Do you mean to redirect the page url after (say 5 seconds) when page is loaded. 

If that's the case, then its a pretty simple use case. I can help you achieve that as well. Let me know the exact requirement.

**Comment by blunderboy** [comment]
@reilue Just let me know your exact use case. From your previous comment, it looks like you want to do the following:

- Redirect a script on the page with a script hosted locally (or may be on github, dropbox etc)
- In that script, wait for DOM ready and after that add a timer of N seconds using `setTimeout` and after the timer, use
    window.location = 'http://new-domain.com';

Your code should look like this

    $(document).ready(function() {
      setTimeout(function() {
        window.location = 'http://new-domain.com';
      });
    });


I think this is what you want.

**Comment by blunderboy** [comment]
Closing this due to lack of response. @reilue Please leave a comment in case you want to continue the discussion or any further help is required.
