### ISSUE TITLE
Do not reload page when rule is changed/created

### ISSUE THREAD

**Issue by blunderboy** [requestly/chrome-extension#92]
With #34, page is refreshed whenever:

- [x] Rule is created
- [x] Rule is modified
- [x] Rule is activated/deactivated
- [x] Rule is Deleted
- [x] Rules are imported.

Please check for following cases and remove the code for refreshing the page.

@harrysingh Please test for all rules and their working against their activation status.

**Comment by harrysingh** [comment]
Made changes and raised PR https://github.com/requestly/chrome-extension/pull/96

**Comment by blunderboy** [comment]
@harrysingh Please add In Progress label when you are working on an issue and remove it before closing the task

**Comment by blunderboy** [comment]
@harrysingh We are good to go away with this task. I am removing Add Unit Tests subtask from this ticket. We can submit unit tests against the following issue.

https://github.com/requestly/chrome-extension/issues/38

Closing this.
