### ISSUE TITLE
Handle trailing slash in Urls with "Equals" Operator

### ISSUE THREAD

**Issue by blunderboy** [requestly/chrome-extension#94]
Equals operator in Redirect, Cancel and Headers rule performs strict checking.

For Example:

Url Equals https://www.facebook.com will not match https://www.facebook.com/

When chrome makes requests for facebook and other top level domains, path is considered as "/" by default. So, above Rule will not match and User has to specify a "/" after the source value in rule but most of the users are not aware of this and end up thinking it is not working.

@harrysingh You can work on this one after Issue #92.

**Comment by harrysingh** [comment]
Made chanages and raised PR https://github.com/requestly/chrome-extension/pull/97

**Comment by blunderboy** [comment]
@harrysingh Let us pick up this one once Issue #92 is done. Removed "In Progress" label for now. Let us pick issues one by one.

**Comment by blunderboy** [comment]
PR: https://github.com/requestly/chrome-extension/pull/99 has been merged. Closing this issue.
