### ISSUE TITLE
Event passing strategy Improvement for analytics tracking

### ISSUE THREAD

**Issue by harrysingh** [requestly/chrome-extension#95]
While fixing #92, we observed
There are JS errors on rule import and delete and was getting ignored due to page reload.
commented the code to track event for now.

Need to Fix the issue.

CC: @blunderboy

**Comment by blunderboy** [comment]
This commit https://github.com/requestly/web/commit/b6fa22e9df74bb9629c3b948ea2190a3192b7d84 seems to fix this issue.

**Comment by blunderboy** [comment]
Looks like this issue has been fixed, closing this one.
